---
title: "Data Analytic Report 2"
author: "Julissa Duenas"
date: "3/4/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Question 1:
a)
```{r}
base = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/'
death = 'time_series_covid19_deaths_'
confirm = 'time_series_covid19_confirmed_'

###up-to-date US death and confirmed cases
us_death = read.csv(paste0(base,death,"US.csv"))
us_confirm = read.csv(paste0(base,confirm,"US.csv"))
col_names = colnames(us_death)
all_dates = as.Date(paste0(str_sub(col_names[13:dim(us_confirm)[2]], 2, -1), "20"), tryFormats = c("%m.%d.%Y"))
covid19_project_url = "https://api.covidtracking.com/v1/states/daily.csv"

covid_19_project = read.csv(covid19_project_url)

covid_19_project$date = as.Date(as.character(covid_19_project$date), "%Y %m %d")
covid_19_project$date
nation_confirmed = us_confirm %>%
  dplyr::filter(Country_Region == "US")
nation_confirmed_sum = apply(nation_confirmed[,12:dim(nation_confirmed)[2]], 2, sum)
start_date=as.Date('2020-4-1')
end_date=as.Date('2020-12-1')
nation_confirmed_selected = nation_confirmed_sum[which(all_dates %in% seq.Date(start_date, end_date, by=1))]
nation_confirmed_selected=as.numeric(nation_confirmed_selected)
date_selected=seq.Date(start_date, end_date, by=1)
daily_date_selected=date_selected[2:length(date_selected)]

#Daily confirmed cases
nation_confirmed_selected_daily=nation_confirmed_selected[2:length(nation_confirmed_selected)]-nation_confirmed_selected[1:(length(nation_confirmed_selected)-1)]
daily_confirmed_nation_df = data.frame(date = daily_date_selected, value = nation_confirmed_selected_daily)
nation_confirmed_selected_daily_avg = data_seven_day_smoothing(nation_confirmed_selected_daily)
daily_confirmed_nation_smoothed_df = data.frame(date = daily_date_selected, value = nation_confirmed_selected_daily_avg)
daily_confirmed_nation_smoothed_df %>%
  ggplot(aes(x=date, y=value)) +
  geom_bar(stat = 'identity', color="white",  fill="#ff8540", width = 1) +
  ylab("7-day averaged daily confirmed cases in  US")+
  xlab("Date")+ 
  theme(text = element_text(size = 20),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.key.width=unit(1,"cm"),
        axis.text.y = element_text(angle=90, hjust=1))

```
```{r}
nation_test = covid_19_project %>%  
  dplyr::select(date, state,totalTestResultsIncrease, positiveIncrease)
nation_test_aggregated = nation_test %>%
  group_by(date) %>%
  summarise_each(funs(sum), positiveIncrease, totalTestResultsIncrease)
nation_test_aggregated$positiveIncrease_7_day_avg = data_seven_day_smoothing(nation_test_aggregated$positiveIncrease)
nation_test_aggregated$totalTestResultsIncrease_7_day_avg = data_seven_day_smoothing(nation_test_aggregated$totalTestResultsIncrease)
nation_test_aggregated$positive_rate = nation_test_aggregated$positiveIncrease_7_day_avg / nation_test_aggregated$totalTestResultsIncrease_7_day_avg
us_test_daily_test_smoothed = data_seven_day_smoothing(nation_test_aggregated$totalTestResultsIncrease)
us_test_daily_positive_smoothed  = data_seven_day_smoothing(nation_test_aggregated$positiveIncrease)
us_test_PositiveRate_smoothed = us_test_daily_positive_smoothed / us_test_daily_test_smoothed

us_test_PositiveRate_smoothed_selected=us_test_PositiveRate_smoothed[nation_test_aggregated$date>=(start_date) & nation_test_aggregated$date<=end_date]
plot(date_selected, us_test_PositiveRate_smoothed_selected,type='l',xlab='date',ylab='-day averaged daily positive rate')

```
```{r}
start_date=as.Date('2020-4-15')
end_date=as.Date('2020-7-15')
nation_confirmed_selected = nation_confirmed_sum[which(all_dates %in% seq.Date(start_date, end_date, by=1))]
nation_confirmed_selected=as.numeric(nation_confirmed_selected)
date_selected=seq.Date(start_date, end_date, by=1)
daily_date_selected=date_selected[2:length(date_selected)]

#Daily confirmed cases
nation_confirmed_selected_daily=nation_confirmed_selected[2:length(nation_confirmed_selected)]-nation_confirmed_selected[1:(length(nation_confirmed_selected)-1)]
daily_confirmed_nation_df = data.frame(date = daily_date_selected, value = nation_confirmed_selected_daily)
nation_confirmed_selected_daily_avg = data_seven_day_smoothing(nation_confirmed_selected_daily)
daily_confirmed_nation_smoothed_df = data.frame(date = daily_date_selected, value = nation_confirmed_selected_daily_avg)
daily_confirmed_nation_smoothed_df %>%
  ggplot(aes(x=date, y=value)) +
  geom_bar(stat = 'identity', color="white",  fill="#ff8540", width = 1) +
  ylab("7-day averaged daily confirmed cases in  US")+
  xlab("Date")+ 
  theme(text = element_text(size = 20),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.key.width=unit(1,"cm"),
        axis.text.y = element_text(angle=90, hjust=1))
```
```{r}
nation_test = covid_19_project %>%  
  dplyr::select(date, state,totalTestResultsIncrease, positiveIncrease)
nation_test_aggregated = nation_test %>%
  group_by(date) %>%
  summarise_each(funs(sum), positiveIncrease, totalTestResultsIncrease)
nation_test_aggregated$positiveIncrease_7_day_avg = data_seven_day_smoothing(nation_test_aggregated$positiveIncrease)
nation_test_aggregated$totalTestResultsIncrease_7_day_avg = data_seven_day_smoothing(nation_test_aggregated$totalTestResultsIncrease)
nation_test_aggregated$positive_rate = nation_test_aggregated$positiveIncrease_7_day_avg / nation_test_aggregated$totalTestResultsIncrease_7_day_avg
us_test_daily_test_smoothed = data_seven_day_smoothing(nation_test_aggregated$totalTestResultsIncrease)
us_test_daily_positive_smoothed  = data_seven_day_smoothing(nation_test_aggregated$positiveIncrease)
us_test_PositiveRate_smoothed = us_test_daily_positive_smoothed / us_test_daily_test_smoothed

us_test_PositiveRate_smoothed_selected=us_test_PositiveRate_smoothed[nation_test_aggregated$date>=(start_date) & nation_test_aggregated$date<=end_date]
plot(date_selected, us_test_PositiveRate_smoothed_selected,type='l',xlab='date',ylab='-day averaged daily positive rate')
```

b)
```{r}
us_confirm_death_clean = clean_JHU_data_for_map(us_confirm, us_death)

us_confirm_clean = us_confirm_death_clean[[1]]
us_death_clean = us_confirm_death_clean[[2]]
us_daily_confirm_clean = us_confirm_clean
us_daily_confirm_clean[,12] = NA
us_daily_confirm_clean[,13:dim(us_confirm_clean)[2]] = t(apply(us_confirm_clean[12:dim(us_confirm_clean)[2]], 1, diff))
us_daily_death_clean = us_death_clean
us_daily_death_clean[,13] = NA
us_daily_death_clean[,14:dim(us_death_clean)[2]] = t(apply(us_death_clean[13:dim(us_death_clean)[2]], 1, diff))
nation_population = us_daily_death_clean$Population
date_for_map='2020-04-20'
nation_daily_confirmed_selected = us_daily_confirm_clean[, c(1:11, 11+which(all_dates==date_for_map))]
nation_daily_confirmed_rate_selected = nation_daily_confirmed_selected
nation_daily_confirmed_rate_selected[,12] = nation_daily_confirmed_selected[,12] / nation_population
nation_daily_confirmed_rate_selected[,12][nation_daily_confirmed_rate_selected[,12] == 0] = NA
colnames(nation_daily_confirmed_rate_selected)[12] = "Ratio"
nation_daily_confirmed_rate_selected_joint <- left_join(nation_daily_confirmed_rate_selected, counties, by = "county_fips")
nation_daily_confirmed_rate_selected_joint %>%
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = (Ratio*100)), show.legend = T) +
  geom_polygon(
    data = urbnmapr::states, mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = 'black', size = 1
  ) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey90", trans = "log10"
                      ###, limits = c(0.00038, 1.158)
                      )+
  coord_map() +
  labs(fill = expression("Ratio (%)")) +
  ggtitle(paste0("daily confirmed cases / population in the U.S.", ", ", date_for_map))

```
```{r}
date_for_map='2020-07-20'
nation_daily_confirmed_selected = us_daily_confirm_clean[, c(1:11, 11+which(all_dates==date_for_map))]
nation_daily_confirmed_rate_selected = nation_daily_confirmed_selected
nation_daily_confirmed_rate_selected[,12] = nation_daily_confirmed_selected[,12] / nation_population
nation_daily_confirmed_rate_selected[,12][nation_daily_confirmed_rate_selected[,12] == 0] = NA
colnames(nation_daily_confirmed_rate_selected)[12] = "Ratio"
nation_daily_confirmed_rate_selected_joint <- left_join(nation_daily_confirmed_rate_selected, counties, by = "county_fips")
nation_daily_confirmed_rate_selected_joint %>%
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = (Ratio*100)), show.legend = T) +
  geom_polygon(
    data = urbnmapr::states, mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = 'black', size = 1
  ) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey90", trans = "log10"
                      ###, limits = c(0.00038, 1.158)
                      )+
  coord_map() +
  labs(fill = expression("Ratio (%)")) +
  ggtitle(paste0("daily confirmed cases / population in the U.S.", ", ", date_for_map))
```
```{r}
date_for_map='2020-10-20'
nation_daily_confirmed_selected = us_daily_confirm_clean[, c(1:11, 11+which(all_dates==date_for_map))]
nation_daily_confirmed_rate_selected = nation_daily_confirmed_selected
nation_daily_confirmed_rate_selected[,12] = nation_daily_confirmed_selected[,12] / nation_population
nation_daily_confirmed_rate_selected[,12][nation_daily_confirmed_rate_selected[,12] == 0] = NA
colnames(nation_daily_confirmed_rate_selected)[12] = "Ratio"
nation_daily_confirmed_rate_selected_joint <- left_join(nation_daily_confirmed_rate_selected, counties, by = "county_fips")
nation_daily_confirmed_rate_selected_joint %>%
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = (Ratio*100)), show.legend = T) +
  geom_polygon(
    data = urbnmapr::states, mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = 'black', size = 1
  ) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey90", trans = "log10"
                      ###, limits = c(0.00038, 1.158)
                      )+
  coord_map() +
  labs(fill = expression("Ratio (%)")) +
  ggtitle(paste0("daily confirmed cases / population in the U.S.", ", ", date_for_map))
```

Question 2:
a)
```{r}
start_date=as.Date('2020-07-01')
end_date=as.Date('2020-11-01')
date_selected=seq.Date(start_date,end_date,by=1)
state_name='Michigan'
county_name='Michigan'
state_name_short='MI'
state_comfirmed=us_confirm%>%filter(Province_State==state_name)%>%select(starts_with('x'))
state_confirmed_sum=apply(state_comfirmed,2,sum)
state_confirmed_selected=state_confirmed_sum[which(all_dates%in%seq.Date(start_date,end_date,by=1))]
state_confirmed_selected=as.numeric(state_confirmed_selected)
state_confirmed_selected_daily=state_confirmed_selected[2:length(state_confirmed_selected)]-state_confirmed_selected[1:(length(state_confirmed_selected)-1)]
daily_date_selected=date_selected[2:length(date_selected)]
daily_confirmed_state_df = data.frame(date = daily_date_selected, value = state_confirmed_selected_daily)

state_confirmed_selected_daily_avg = data_seven_day_smoothing(state_confirmed_selected_daily)
daily_confirmed_state_avg_df = data.frame(date = daily_date_selected, value = state_confirmed_selected_daily_avg)

daily_confirmed_state_avg_df %>%
  ggplot(aes(x=date, y=value)) +
  geom_bar(stat = 'identity', color="white",  fill="#ff8540", width = 1) +
  ylab("Daily confirmed cases in Michigan")+
  xlab("Date")+ 
  theme(text = element_text(size = 20),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.key.width=unit(1,"cm"),
        axis.text.y = element_text(angle=90, hjust=1))

```
```{r}
state_test=covid_19_project%>%filter(state=='MI')%>%  
  dplyr::select(date, state,totalTestResultsIncrease, positiveIncrease)
state_test_aggregated = state_test %>%
  group_by(date) %>%
  summarise_each(funs(sum), positiveIncrease, totalTestResultsIncrease)
state_test_aggregated$positiveIncrease_7_day_avg = data_seven_day_smoothing(state_test_aggregated$positiveIncrease)

state_test_aggregated$totalTestResultsIncrease_7_day_avg = data_seven_day_smoothing(state_test_aggregated$totalTestResultsIncrease)

state_test_aggregated$positive_rate = state_test_aggregated$positiveIncrease_7_day_avg / state_test_aggregated$totalTestResultsIncrease_7_day_avg

michigan_test_daily_test_smoothed = data_seven_day_smoothing(state_test_aggregated$totalTestResultsIncrease)
michigan_test_daily_positive_smoothed  = data_seven_day_smoothing(state_test_aggregated$positiveIncrease)
michigan_test_PositiveRate_smoothed = michigan_test_daily_positive_smoothed / michigan_test_daily_test_smoothed

michigan_test_PositiveRate_smoothed_selected=michigan_test_PositiveRate_smoothed[state_test_aggregated$date>=(start_date) & state_test_aggregated$date<=end_date]

plot(date_selected,michigan_test_PositiveRate_smoothed_selected,type='l',xlab='date',ylab='7-day averaged daily positive rate')

```

b)
```{r}
date_for_map='2020-07-01'
michigan_daily_confirm_selected=us_daily_confirm_clean[us_daily_confirm_clean$Province_State=='Michigan',c(1:11,11+which(all_dates==date_for_map))]
state_population = us_daily_death_clean %>%
  filter(Province_State == 'Michigan')%>%
  dplyr::select(Population)

michigan_daily_confirm_rate_selected = michigan_daily_confirm_selected
michigan_daily_confirm_rate_selected[,12] = michigan_daily_confirm_selected[,12]/state_population
michigan_daily_confirm_rate_selected[,12][michigan_daily_confirm_rate_selected[,12]==0]=NA
colnames(michigan_daily_confirm_rate_selected)[12] = "Ratio"
michigan_daily_confirm_rate_selected_joint <- left_join(michigan_daily_confirm_rate_selected,counties,by='county_fips')

michigan_daily_confirm_rate_selected_joint %>%
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = (Ratio*100)), show.legend = T) +
  geom_polygon(
    data = urbnmapr::states[urbnmapr::states$state_name=='Michigan'
                            ,], mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = 'black', size = 1
  ) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey90", trans = "log10"
                      ###, limits = c(0.00038, 1.158)
                      )+
  coord_map() +
  labs(fill = expression("Ratio (%)")) +
  ggtitle(paste0("daily confirmed cases / population in the U.S.", ", ", date_for_map))


```
```{r}
date_for_map='2020-10-01'
michigan_daily_confirm_selected=us_daily_confirm_clean[us_daily_confirm_clean$Province_State=='Michigan',c(1:11,11+which(all_dates==date_for_map))]
state_population = us_daily_death_clean %>%
  filter(Province_State == 'Michigan')%>%
  dplyr::select(Population)

michigan_daily_confirm_rate_selected = michigan_daily_confirm_selected
michigan_daily_confirm_rate_selected[,12] = michigan_daily_confirm_selected[,12]/state_population
michigan_daily_confirm_rate_selected[,12][michigan_daily_confirm_rate_selected[,12]==0]=NA
colnames(michigan_daily_confirm_rate_selected)[12] = "Ratio"
michigan_daily_confirm_rate_selected_joint <- left_join(michigan_daily_confirm_rate_selected,counties,by='county_fips')

michigan_daily_confirm_rate_selected_joint %>%
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = (Ratio*100)), show.legend = T) +
  geom_polygon(
    data = urbnmapr::states[urbnmapr::states$state_name=='Michigan'
                            ,], mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = 'black', size = 1
  ) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey90", trans = "log10"
                      ###, limits = c(0.00038, 1.158)
                      )+
  coord_map() +
  labs(fill = expression("Ratio (%)")) +
  ggtitle(paste0("daily confirmed cases / population in the U.S.", ", ", date_for_map))

```

c)
```{r}
date_for_map='2020-10-10'
michigan_daily_confirm_selected=us_daily_confirm_clean[us_daily_confirm_clean$Province_State=='Michigan',c(1:11,11+which(all_dates==date_for_map))]
state_population = us_daily_death_clean %>%
  filter(Province_State == 'Michigan')%>%
  dplyr::select(Population)

michigan_daily_confirm_rate_selected = michigan_daily_confirm_selected
michigan_daily_confirm_rate_selected[,12] = michigan_daily_confirm_selected[,12]/state_population
michigan_daily_confirm_rate_selected[,12][michigan_daily_confirm_rate_selected[,12]==0]=NA
colnames(michigan_daily_confirm_rate_selected)[12] = "Ratio"
michigan_daily_confirm_rate_selected_joint <- left_join(michigan_daily_confirm_rate_selected,counties,by='county_fips')

michigan_daily_confirm_rate_selected_joint %>%
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = (Ratio*100)), show.legend = T) +
  geom_polygon(
    data = urbnmapr::states[urbnmapr::states$state_name=='Michigan'
                            ,], mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = 'black', size = 1
  ) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey90", trans = "log10"
                      ###, limits = c(0.00038, 1.158)
                      )+
  coord_map() +
  labs(fill = expression("Ratio (%)")) +
  ggtitle(paste0("daily confirmed cases / population in Michigan", ", ", date_for_map))

```
```{r}
date_for_map='2020-10-20'
michigan_daily_confirm_selected=us_daily_confirm_clean[us_daily_confirm_clean$Province_State=='Michigan',c(1:11,11+which(all_dates==date_for_map))]
state_population = us_daily_death_clean %>%
  filter(Province_State == 'Michigan')%>%
  dplyr::select(Population)

michigan_daily_confirm_rate_selected = michigan_daily_confirm_selected
michigan_daily_confirm_rate_selected[,12] = michigan_daily_confirm_selected[,12]/state_population
michigan_daily_confirm_rate_selected[,12][michigan_daily_confirm_rate_selected[,12]==0]=NA
colnames(michigan_daily_confirm_rate_selected)[12] = "Ratio"
michigan_daily_confirm_rate_selected_joint <- left_join(michigan_daily_confirm_rate_selected,counties,by='county_fips')

michigan_daily_confirm_rate_selected_joint %>%
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = (Ratio*100)), show.legend = T) +
  geom_polygon(
    data = urbnmapr::states[urbnmapr::states$state_name=='Michigan'
                            ,], mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = 'black', size = 1
  ) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey90", trans = "log10"
                      ###, limits = c(0.00038, 1.158)
                      )+
  coord_map() +
  labs(fill = expression("Ratio (%)")) +
  ggtitle(paste0("daily confirmed cases / population in the U.S.", ", ", date_for_map))

```
```{r}
date_for_map='2020-10-30'
michigan_daily_confirm_selected=us_daily_confirm_clean[us_daily_confirm_clean$Province_State=='Michigan',c(1:11,11+which(all_dates==date_for_map))]
state_population = us_daily_death_clean %>%
  filter(Province_State == 'Michigan')%>%
  dplyr::select(Population)

michigan_daily_confirm_rate_selected = michigan_daily_confirm_selected
michigan_daily_confirm_rate_selected[,12] = michigan_daily_confirm_selected[,12]/state_population
michigan_daily_confirm_rate_selected[,12][michigan_daily_confirm_rate_selected[,12]==0]=NA
colnames(michigan_daily_confirm_rate_selected)[12] = "Ratio"
michigan_daily_confirm_rate_selected_joint <- left_join(michigan_daily_confirm_rate_selected,counties,by='county_fips')

michigan_daily_confirm_rate_selected_joint %>%
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = (Ratio*100)), show.legend = T) +
  geom_polygon(
    data = urbnmapr::states[urbnmapr::states$state_name=='Michigan'
                            ,], mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = 'black', size = 1
  ) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey90", trans = "log10"
                      ###, limits = c(0.00038, 1.158)
                      )+
  coord_map() +
  labs(fill = expression("Ratio (%)")) +
  ggtitle(paste0("daily confirmed cases / population in the U.S.", ", ", date_for_map))

```

Question 3:
a)
```{r}
florida_confirmed=us_confirm%>%dplyr::filter(Province_State=='Florida')
start_date=as.Date('2020-07-01')
end_date=as.Date('2020-11-01')
all_dates = as.Date(paste0(str_sub(col_names[13:dim(us_confirm)[2]], 2, -1), "20"), tryFormats = c("%m.%d.%Y"))

florida_confirmed_sum = apply(florida_confirmed[,12:dim(florida_confirmed)[2]], 2, sum)
florida_confirmed_selected = florida_confirmed_sum[which(all_dates %in% seq.Date(start_date, end_date, by=1))]

date_selected=seq.Date(start_date, end_date, by=1)
plot(date_selected,florida_confirmed_selected,xlab='date',ylab='cumulative observed confirmed cases',type='l')
```
```{r}
end_date=as.Date('2020-12-01')
date_selected=seq.Date(start_date, end_date, by=1)
state_test=covid_19_project%>%filter(state=='FL')%>%  
  dplyr::select(date, state,totalTestResultsIncrease, positiveIncrease)
state_test_aggregated = state_test %>%
  group_by(date) %>%
  summarise_each(funs(sum), positiveIncrease, totalTestResultsIncrease)
state_test_aggregated$positiveIncrease_7_day_avg = data_seven_day_smoothing(state_test_aggregated$positiveIncrease)

state_test_aggregated$totalTestResultsIncrease_7_day_avg = data_seven_day_smoothing(state_test_aggregated$totalTestResultsIncrease)

state_test_aggregated$positive_rate = state_test_aggregated$positiveIncrease_7_day_avg / state_test_aggregated$totalTestResultsIncrease_7_day_avg

florida_test_daily_test_smoothed = data_seven_day_smoothing(state_test_aggregated$totalTestResultsIncrease)
florida_test_daily_positive_smoothed  = data_seven_day_smoothing(state_test_aggregated$positiveIncrease)
florida_test_PositiveRate_smoothed = florida_test_daily_positive_smoothed / florida_test_daily_test_smoothed

florida_test_PositiveRate_smoothed_selected=florida_test_PositiveRate_smoothed[state_test_aggregated$date>=(start_date) & state_test_aggregated$date<=end_date]

plot(date_selected,florida_test_PositiveRate_smoothed_selected,type='l',xlab='date',ylab='7-day averaged daily positive rate')
```

b)
```{r}
date_for_map='2020-07-01'
florida_daily_confirm_selected=us_daily_confirm_clean[us_daily_confirm_clean$Province_State=='Florida',c(1:11,11+which(all_dates==date_for_map))]
state_population = us_daily_death_clean %>%
  filter(Province_State == 'Florida')%>%
  dplyr::select(Population)

florida_daily_confirm_rate_selected = florida_daily_confirm_selected
florida_daily_confirm_rate_selected[,12] = florida_daily_confirm_selected[,12]/state_population
florida_daily_confirm_rate_selected[,12][florida_daily_confirm_rate_selected[,12]==0]=NA
colnames(florida_daily_confirm_rate_selected)[12] = "Ratio"
florida_daily_confirm_rate_selected_joint <- left_join(florida_daily_confirm_rate_selected,counties,by='county_fips')

florida_daily_confirm_rate_selected_joint %>%
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = (Ratio*100)), show.legend = T) +
  geom_polygon(
    data = urbnmapr::states[urbnmapr::states$state_name=='Florida'
                            ,], mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = 'black', size = 1
  ) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey90", trans = "log10"
                      ###, limits = c(0.00038, 1.158)
                      )+
  coord_map() +
  labs(fill = expression("Ratio (%)")) +
  ggtitle(paste0("daily confirmed cases / population in Florida", ", ", date_for_map))
```
```{r}
date_for_map='2020-11-01'
florida_daily_confirm_selected=us_daily_confirm_clean[us_daily_confirm_clean$Province_State=='Florida',c(1:11,11+which(all_dates==date_for_map))]
state_population = us_daily_death_clean %>%
  filter(Province_State == 'Florida')%>%
  dplyr::select(Population)

florida_daily_confirm_rate_selected = florida_daily_confirm_selected
florida_daily_confirm_rate_selected[,12] = florida_daily_confirm_selected[,12]/state_population
florida_daily_confirm_rate_selected[,12][florida_daily_confirm_rate_selected[,12]==0]=NA
colnames(florida_daily_confirm_rate_selected)[12] = "Ratio"
florida_daily_confirm_rate_selected_joint <- left_join(florida_daily_confirm_rate_selected,counties,by='county_fips')

florida_daily_confirm_rate_selected_joint %>%
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = (Ratio*100)), show.legend = T) +
  geom_polygon(
    data = urbnmapr::states[urbnmapr::states$state_name=='Florida'
                            ,], mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = 'black', size = 1
  ) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey90", trans = "log10"
                      ###, limits = c(0.00038, 1.158)
                      )+
  coord_map() +
  labs(fill = expression("Ratio (%)")) +
  ggtitle(paste0("daily confirmed cases / population in Florida", ", ", date_for_map))

```

Question 4:
a)
```{r}
california_confirmed=us_confirm%>%dplyr::filter(Province_State=='California')
start_date=as.Date('2020-04-01')
end_date=as.Date('2020-12-31')
all_dates = as.Date(paste0(str_sub(col_names[13:dim(us_confirm)[2]], 2, -1), "20"), tryFormats = c("%m.%d.%Y"))

california_confirmed_sum = apply(california_confirmed[,12:dim(california_confirmed)[2]], 2, sum)
california_confirmed_selected = california_confirmed_sum[which(all_dates %in% seq.Date(start_date, end_date, by=1))]

date_selected=seq.Date(start_date, end_date, by=1)
plot(date_selected,california_confirmed_selected,xlab='date',ylab='cumulative observed confirmed cases',type='l')
```
```{r}
end_date=as.Date('2020-11-01')
date_selected=seq.Date(start_date, end_date, by=1)
state_test=covid_19_project%>%filter(state=='CA')%>%  
  dplyr::select(date, state,totalTestResultsIncrease, positiveIncrease)
state_test_aggregated = state_test %>%
  group_by(date) %>%
  summarise_each(funs(sum), positiveIncrease, totalTestResultsIncrease)
state_test_aggregated$positiveIncrease_7_day_avg = data_seven_day_smoothing(state_test_aggregated$positiveIncrease)

state_test_aggregated$totalTestResultsIncrease_7_day_avg = data_seven_day_smoothing(state_test_aggregated$totalTestResultsIncrease)

state_test_aggregated$positive_rate = state_test_aggregated$positiveIncrease_7_day_avg / state_test_aggregated$totalTestResultsIncrease_7_day_avg

california_test_daily_test_smoothed = data_seven_day_smoothing(state_test_aggregated$totalTestResultsIncrease)
california_test_daily_positive_smoothed  = data_seven_day_smoothing(state_test_aggregated$positiveIncrease)
california_test_PositiveRate_smoothed = california_test_daily_positive_smoothed / california_test_daily_test_smoothed

california_test_PositiveRate_smoothed_selected=california_test_PositiveRate_smoothed[state_test_aggregated$date>=(start_date) & state_test_aggregated$date<=end_date]

plot(date_selected,california_test_PositiveRate_smoothed_selected,type='l',xlab='date',ylab='7-day averaged daily positive rate')
```

c)
```{r}
date_for_map='2020-04-01'
california_daily_confirm_selected=us_daily_confirm_clean[us_daily_confirm_clean$Province_State=='California',c(1:11,11+which(all_dates==date_for_map))]
state_population = us_daily_death_clean %>%
  filter(Province_State == 'California')%>%
  dplyr::select(Population)

california_daily_confirm_rate_selected = california_daily_confirm_selected
california_daily_confirm_rate_selected[,12] = california_daily_confirm_selected[,12]/state_population
california_daily_confirm_rate_selected[,12][california_daily_confirm_rate_selected[,12]==0]=NA
colnames(california_daily_confirm_rate_selected)[12] = "Ratio"
california_daily_confirm_rate_selected_joint <- left_join(california_daily_confirm_rate_selected,counties,by='county_fips')

california_daily_confirm_rate_selected_joint %>%
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = (Ratio*100)), show.legend = T) +
  geom_polygon(
    data = urbnmapr::states[urbnmapr::states$state_name=='California'
                            ,], mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = 'black', size = 1
  ) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey90", trans = "log10"
                      ###, limits = c(0.00038, 1.158)
                      )+
  coord_map() +
  labs(fill = expression("Ratio (%)")) +
  ggtitle(paste0("daily confirmed cases / population in California", ", ", date_for_map))
```
```{r}
date_for_map='2020-12-01'
california_daily_confirm_selected=us_daily_confirm_clean[us_daily_confirm_clean$Province_State=='California',c(1:11,11+which(all_dates==date_for_map))]
state_population = us_daily_death_clean %>%
  filter(Province_State == 'California')%>%
  dplyr::select(Population)

california_daily_confirm_rate_selected = california_daily_confirm_selected
california_daily_confirm_rate_selected[,12] = california_daily_confirm_selected[,12]/state_population
california_daily_confirm_rate_selected[,12][california_daily_confirm_rate_selected[,12]==0]=NA
colnames(california_daily_confirm_rate_selected)[12] = "Ratio"
california_daily_confirm_rate_selected_joint <- left_join(california_daily_confirm_rate_selected,counties,by='county_fips')

california_daily_confirm_rate_selected_joint %>%
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = (Ratio*100)), show.legend = T) +
  geom_polygon(
    data = urbnmapr::states[urbnmapr::states$state_name=='California'
                            ,], mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = 'black', size = 1
  ) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey90", trans = "log10"
                      ###, limits = c(0.00038, 1.158)
                      )+
  coord_map() +
  labs(fill = expression("Ratio (%)")) +
  ggtitle(paste0("daily confirmed cases / population in California", ", ", date_for_map))
```

d)
```{r}
set.seed(1)
state_name = "California"
state_name_short = "CA"
county_name_selected = "Santa Barbara"
start_date_ini = as.Date("2020-04-01")
end_date = as.Date("2020-12-01")
file_pow_param_path = "data_and_functions/"
file_sudden_death_path = "data_and_functions/"
base = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/'
death = 'time_series_covid19_deaths_'
confirm = 'time_series_covid19_confirmed_'

# download death and confirmed data from JHU
us_death = read.csv(paste0(base,death,"US.csv"))
us_confirm = read.csv(paste0(base,confirm,"US.csv"))

prediction_length = 60
fitted_days_beta=224 
gamma = 0.2
theta = 0.1
delta = 0.0066
county_sudden_death = read.csv("counties with sudden death increase.csv")
county_sudden_death$state = as.character(county_sudden_death$state)
us_pow_param = read.csv("power parameter in US states.csv")
us_pow_param$state_name = as.character(us_pow_param$state_name)
us_death = clean_us_death(us_death)
col_names = colnames(us_death)
all_dates = as.Date(paste0(str_sub(col_names[13:dim(us_death)[2]], 2, -1), "20"), tryFormats = c("%m.%d.%Y"))
death_rate = function(x){x/us_death$Population*10^6}
us_death_rate = us_death %>%
  dplyr::mutate_at(vars(starts_with("X")), death_rate)
n_ini = as.numeric(end_date - start_date_ini) + 1
power_parameter = as.numeric(us_pow_param$pow_param[us_pow_param$state_name == state_name])
state_test = covid_19_project %>%
  dplyr::filter(state == state_name_short) %>%
  dplyr::select(date, totalTestResultsIncrease, positiveIncrease)
state_test$totalTestResultsIncrease[state_test$totalTestResultsIncrease<0] = abs(state_test$totalTestResultsIncrease[state_test$totalTestResultsIncrease<0])
state_test$positiveIncrease[state_test$positiveIncrease<0] = abs(state_test$positiveIncrease[state_test$positiveIncrease<0])
state_test$daily_test_avg = rep(0, dim(state_test)[1])
state_test$daily_positive_avg = rep(0, dim(state_test)[1])
state_test$daily_test_avg = data_seven_day_smoothing(state_test$totalTestResultsIncrease)
state_test$daily_positive_avg = data_seven_day_smoothing(state_test$positiveIncrease)
state_test$PositiveRate = state_test$daily_positive_avg / state_test$daily_test_avg
for (i in 2:(dim(state_test)[1])) {
  if(is.na(state_test$PositiveRate[i]) | is.infinite(state_test$PositiveRate[i])){
    state_test$PositiveRate[i] = state_test$PositiveRate[i-1]
  }
}
state_test$PositiveRate[is.na(state_test$PositiveRate)] = state_test$PositiveRate[which(!is.na(state_test$PositiveRate))[1]]
# change negative rate to positive
state_test$PositiveRate = abs(state_test$PositiveRate)
# change positive rate larger tha 1 to 1
state_test$PositiveRate[state_test$PositiveRate>1] = 1 / state_test$PositiveRate[state_test$PositiveRate>1]
state_death = us_death %>%
  dplyr::filter(Province_State == state_name)
state_confirmed = us_confirm %>%
  dplyr::filter(Province_State == state_name)
# Part 1: Data Cleaning
# Select the county-level death and confirmed cases
county_death_raw = state_death %>%
  dplyr::filter(Admin2 == county_name_selected)
county_confirm_raw = state_confirmed %>%
  dplyr::filter(Admin2 == county_name_selected)
# the real start date is defined as the date that the state confirmed cases is no less than 5 for the first time
start_date=all_dates[which(as.numeric(county_confirm_raw[12:length(county_confirm_raw)])>=5)[1]]
if (start_date < start_date_ini){
  start_date = start_date_ini
}
# the length of real training period
n = as.numeric(end_date - start_date) + 1

# get county data from real start_date to end_date

death_with_county_names = get_output_same_time_zone(
  data_type = "death",
  state_name = state_name,
  start_date = start_date,
  state_name_short = state_name_short,
  duration = n ,
  training_length = n,
  criterion_death = 2,
  smoothness = F
)




death_with_county_names_all = get_output_same_time_zone(
  data_type = "death",
  state_name = state_name,
  start_date = start_date,
  state_name_short = state_name_short,
  duration = n+prediction_length ,
  training_length = n,
  criterion_death = 2,
  smoothness = F
)
county_names = death_with_county_names[[2]]

each_index = which(county_names == county_name_selected)

state_confirmed_selected = state_confirmed %>%
  dplyr::filter(Admin2 %in% county_names)

state_confirmed_selected = state_confirmed_selected[,12:dim(state_confirmed_selected)[2]]

state_confirmed_selected = state_confirmed_selected[, which(all_dates %in% seq.Date(start_date, end_date, by=1))]
SIRDC_county_population = us_death %>%
  filter(Admin2 == county_name_selected, Province_State == state_name) %>%
  dplyr::select(Population)

# county population
N = SIRDC_county_population$Population

# county death and confirmed cases from real start date to end date
death_selected = death_with_county_names[[1]][each_index, ]
confirm_selected = as.numeric(state_confirmed_selected[each_index,])

# eliminate decreasing trend in the county death data
for( i in 1:(n-1)){
  if (death_selected[i+1]<death_selected[i]){
    death_selected[i+1] = death_selected[i]
  }
}
for( i in 1:(n-1)){
  if (confirm_selected[i+1]<confirm_selected[i]){
    confirm_selected[i+1] = confirm_selected[i]
  }
}

# eliminate the sudden increase of death in several prespecified counties
if(paste0(state_name_short, county_name_selected) %in%   paste0(county_sudden_death$state, county_sudden_death$county)){
  daily_death = diff(death_selected)
  sudden_increase_index = which(daily_death==max(daily_death))[1]
  daily_death[(sudden_increase_index-13):(sudden_increase_index-1)] = daily_death[(sudden_increase_index-13):(sudden_increase_index-1)] + daily_death[sudden_increase_index]/14
  daily_death[sudden_increase_index] = daily_death[sudden_increase_index]/14
  death_selected = c(death_selected[1], cumsum(daily_death) + death_selected[1])
}

# smooth the confirm cases
daily_confirm_selected = diff(confirm_selected)
daily_confirm_selected_avg = data_seven_day_smoothing(daily_confirm_selected)
unadjusted_confirm_selected_smoothed = c(confirm_selected[1], cumsum(daily_confirm_selected_avg) + confirm_selected[1])

daily_positive_rate_selected = rep(0,n)
daily_positive_rate_selected = rev(state_test$PositiveRate[state_test$date>=(start_date) & state_test$date<=end_date])

# calculate the weights
c_t_seq =  daily_positive_rate_selected^(power_parameter)

# adjust the confirmed cases using positive_rate^{power_parameter}
daily_confirm_selected = diff(confirm_selected)
daily_adjusted_confirm_smoothed = data_seven_day_smoothing(daily_confirm_selected * c_t_seq[2:n] )
confirm_selected_smoothed = c(c_t_seq[1] * confirm_selected[1], cumsum(daily_adjusted_confirm_smoothed) + c_t_seq[1] * confirm_selected[1])

# eliminate decreasing trend in the smoothed county confirmed cases
for(i in 2:n){
  if (confirm_selected_smoothed[i]<confirm_selected_smoothed[i-1]){
    confirm_selected_smoothed[i] = confirm_selected_smoothed[i-1]
  }
}


```

```{r}
#Step 2
ui = matrix(c(1,0,-1,0,1,-1), 3,2)
ci = matrix(c(0,0, -((confirm_selected_smoothed[1]*N)/confirm_selected_smoothed[n] -  death_selected[1]-0.1)  ))

I_0_ini = 1000
R_0_ini = 1000

if((I_0_ini + R_0_ini)> abs(ci[3])){
  I_0_ini = abs(ci[3])/4
  R_0_ini = abs(ci[3])/4
}

# do optimization
m_approx = constrOptim(
  c(I_0_ini, R_0_ini),
  loss_approx_beta,
  NULL,
  ui = ui,
  ci = ci,
  death_cases = death_selected,
  confirmed_cases = confirm_selected_smoothed,
  unadjusted_confirm_selected_smoothed = unadjusted_confirm_selected_smoothed,
  N_population = N,
  trianing_length = n,
  fixed_global_params = c(gamma, theta, delta),
  penalty = F,
  fitted_days= fitted_days_beta,
  weight_loss=T
)

I_0 = m_approx$par[1]
R_0 = m_approx$par[2]
```

```{r}
#Step 3
ratio = confirm_selected_smoothed[1]/(I_0+ R_0+ death_selected[1])

ratio_real = confirm_selected[2]/(I_0+ R_0+ death_selected[1])

# use ratio to adjust smoothed confirmed cases and get susceptible cases S_t
estimated_confirm = confirm_selected_smoothed/ratio

# make sure the adjusted confirmed cases is at least larger than the observed confirm cases
for(i in 1:length(estimated_confirm)){
  if (estimated_confirm[i] < unadjusted_confirm_selected_smoothed[i]){
    estimated_confirm[i] = unadjusted_confirm_selected_smoothed[i]
  }
}

S_t_seq = N - estimated_confirm

# initial values of each compartment
init_for_beta = c(S_t_seq[1], I_0, R_0, death_selected[1], 0)

param_record_approx_for_beta = matrix(0, 5, n) # 5 rows: S_t, I_t, R_t, D_t, C_t
param_record_approx_for_beta[,1] = init_for_beta
param_record_approx_for_beta[1,] = S_t_seq

# record the value of transmission rate
approx_beta_seq = rep(0, n-1)
for (i in 1:(n-1)){
  S_t_1 = param_record_approx_for_beta[1,i]
  S_t_2 = param_record_approx_for_beta[1,i+1]
  I_t_1 = param_record_approx_for_beta[2,i]
  R_t_1 = param_record_approx_for_beta[3,i]
  D_t_1 = param_record_approx_for_beta[4,i]
  C_t_1 = param_record_approx_for_beta[5,i]
  
  if(I_t_1<1){
    I_t_1 = 1
  }
  
  beta_t_1_2 = uniroot(find_root_beta, c(0, 10^6), tol = 0.0001, param = c(S_t_1, S_t_2, I_t_1), N = N, gamma=gamma)
  
  I_t_2 = I_t_1 * exp(beta_t_1_2$root*(S_t_1 + S_t_2)/(2*N) - gamma)
  R_t_2 = (2-theta)/(2+theta)*R_t_1 + gamma/(2+theta)*(I_t_1+I_t_2)
  D_t_2 = D_t_1 + delta*theta*(R_t_1+R_t_2)/2
  C_t_2 = C_t_1 + (1-delta)*theta*(R_t_1+R_t_2)/2
  
  param_record_approx_for_beta[2:5, i+1] = c(I_t_2, R_t_2, D_t_2, C_t_2)
  approx_beta_seq[i] = beta_t_1_2$root
}

# calculate the smoothed transmission rate using 7 day average
approx_beta_seq_smoothed = rollapply(approx_beta_seq, width = 7, by = 1, FUN = mean, align = "left")

```

```{r}
#Part 4
param_record_approx_all = matrix(0, 5, n+prediction_length) # 5 rows: S_t, I_t, R_t, D_t, C_t
param_record_approx_all[,1] = init_for_beta

approx_beta_seq_all = c(approx_beta_seq, rep(approx_beta_seq[n-1], prediction_length))

for (i in 1:(n+prediction_length-1)){
  S_t_1 = param_record_approx_all[1,i]
  I_t_1 = param_record_approx_all[2,i]
  R_t_1 = param_record_approx_all[3,i]
  D_t_1 = param_record_approx_all[4,i]
  C_t_1 = param_record_approx_all[5,i]
  
  beta_t_1_2 = approx_beta_seq_all[i]
  
  if(I_t_1<1){
    I_t_1 = 1
  }
  
  S_t_2 = uniroot(find_root_S_t_2, c(0, N), tol = 0.0001, param = c(S_t_1, beta_t_1_2, I_t_1), N = N, gamma=gamma)
  I_t_2 = I_t_1 * exp(beta_t_1_2*(S_t_1 + S_t_2$root)/(2*N) - gamma)
  R_t_2 = (2-theta)/(2+theta)*R_t_1 + gamma/(2+theta)*(I_t_1+I_t_2)
  D_t_2 = D_t_1 + delta*theta*(R_t_1+R_t_2)/2
  C_t_2 = C_t_1 + (1-delta)*theta*(R_t_1+R_t_2)/2
  
  param_record_approx_all[, i+1] = c(S_t_2$root, I_t_2, R_t_2, D_t_2, C_t_2)
  
}
```

```{r}
date_seq_beta = seq.Date(start_date, end_date-1, by=1)
date_seq_beta_smoothed = seq.Date(start_date+3, end_date-1-3, by=1)

y_limit_R_t = c(min(approx_beta_seq/0.2), max(approx_beta_seq/0.2))
date_seq = seq.Date(start_date, end_date, by=1)
plot(N-param_record_approx_for_beta[1,]~date_seq, type="l", col="blue", xlab = "Date", ylab = "Infective Cases", main = paste0(county_names[each_index], ", population=", round(N/10^6,2),"M", ", Ratio = ", round(ratio_real,3)))
lines(confirm_selected~date_seq, type="l", col="red")
legend("topleft", legend = c("Estimated Confirmed Cases", "Observed Confirmed Cases"), lty = c(1,1), col = c("red", "blue"))

```
```{r}
print(paste('observed:', confirm_selected[n]))
print(paste('estimated:',N-param_record_approx_for_beta[1,][n]))
```

e)
```{r}

date_seq_all = seq.Date(start_date, end_date+prediction_length, by=1)

ylimit_death_all = c(min(param_record_approx_all[4,], death_selected), max(param_record_approx_all[4,], death_selected))

plot(param_record_approx_all[4,]~date_seq_all,ylim = ylimit_death_all, type="l", col="blue", xlab = "Date", ylab = "Death Cases", main = paste0(county_names[each_index], ", population=", round(N/10^6,2),"M", ", Ratio = ", round(ratio_real,3)))
lines(death_selected~date_seq, col = "red")
lines(date_seq_all[(n+1):(n+prediction_length-1) ],death_with_county_names_all[[1]][each_index,(n+1):(n+prediction_length-1) ], 
      col = "red",lty=2)
abline(v = end_date+1, lty=2)
legend("topleft", legend = c("Observed death toll", "Estimated death toll","Held-out death toll"), lty = c(1,1,2), col = c("red", "blue",'red'))


```

g)
```{r}
gamma_new = 1/4.75 

param_record_approx_for_beta_new = matrix(0, 5, n) 
param_record_approx_for_beta_new[,1] = init_for_beta
param_record_approx_for_beta_new[1,] = S_t_seq
for (i in 1:(n-1)){
  S_t_1 = param_record_approx_for_beta_new[1,i]
  I_t_1 = param_record_approx_for_beta_new[2,i]
  R_t_1 = param_record_approx_for_beta_new[3,i]
  D_t_1 = param_record_approx_for_beta_new[4,i]
  C_t_1 = param_record_approx_for_beta_new[5,i]
  
  beta_t_1_2 = approx_beta_seq[i]
  
  if(I_t_1<1){
    I_t_1 = 1
  }
  
  S_t_2 = uniroot(find_root_S_t_2, c(0, N), tol = 0.0001, param = c(S_t_1, beta_t_1_2, I_t_1), N = N, gamma=gamma_new)
  I_t_2 = I_t_1 * exp(beta_t_1_2*(S_t_1 + S_t_2$root)/(2*N) - gamma_new)
  R_t_2 = (2-theta)/(2+theta)*R_t_1 + gamma_new/(2+theta)*(I_t_1+I_t_2)
  D_t_2 = D_t_1 + delta*theta*(R_t_1+R_t_2)/2
  C_t_2 = C_t_1 + (1-delta)*theta*(R_t_1+R_t_2)/2
  
  param_record_approx_for_beta_new[, i+1] = c(S_t_2$root, I_t_2, R_t_2, D_t_2, C_t_2)
}
plot(param_record_approx_for_beta_new[4,]~date_seq,ylim = ylimit_death, type="l", col="blue", xlab = "Date", ylab = "Death Cases", main = paste0(county_names[each_index], ", population=", round(N/10^6,2),"M", ", Ratio = ", round(ratio_real,3)))
lines(death_selected~date_seq, col = "red")
legend("topleft", legend = c("Observed death toll", "Simulated death toll"), lty = c(1,1), col = c("red", "blue"))

```

h)
```{r}
gamma_new = 1/4.5 

param_record_approx_for_beta_new = matrix(0, 5, n) 
param_record_approx_for_beta_new[,1] = init_for_beta
param_record_approx_for_beta_new[1,] = S_t_seq
for (i in 1:(n-1)){
  S_t_1 = param_record_approx_for_beta_new[1,i]
  I_t_1 = param_record_approx_for_beta_new[2,i]
  R_t_1 = param_record_approx_for_beta_new[3,i]
  D_t_1 = param_record_approx_for_beta_new[4,i]
  C_t_1 = param_record_approx_for_beta_new[5,i]
  
  beta_t_1_2 = approx_beta_seq[i]
  
  if(I_t_1<1){
    I_t_1 = 1
  }
  
  S_t_2 = uniroot(find_root_S_t_2, c(0, N), tol = 0.0001, param = c(S_t_1, beta_t_1_2, I_t_1), N = N, gamma=gamma_new)
  I_t_2 = I_t_1 * exp(beta_t_1_2*(S_t_1 + S_t_2$root)/(2*N) - gamma_new)
  R_t_2 = (2-theta)/(2+theta)*R_t_1 + gamma_new/(2+theta)*(I_t_1+I_t_2)
  D_t_2 = D_t_1 + delta*theta*(R_t_1+R_t_2)/2
  C_t_2 = C_t_1 + (1-delta)*theta*(R_t_1+R_t_2)/2
  
  param_record_approx_for_beta_new[, i+1] = c(S_t_2$root, I_t_2, R_t_2, D_t_2, C_t_2)
}
plot(param_record_approx_for_beta_new[4,]~date_seq,ylim = ylimit_death, type="l", col="blue", xlab = "Date", ylab = "Death Cases", main = paste0(county_names[each_index], ", population=", round(N/10^6,2),"M", ", Ratio = ", round(ratio_real,3)))
lines(death_selected~date_seq, col = "red")
legend("topleft", legend = c("Observed death toll", "Simulated death toll"), lty = c(1,1), col = c("red", "blue"))
```

